spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   #update   create-drop  create validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: news_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS news_schema
      connection-timeout: 10000
server:
  port: 8081

#    hibernate:
#      connection:
#        driver_class: org.postgresql.Driver
#        url: jdbc:postgresql://localhost:5432/news_db
#        username: postgres
#        password: postgres
#      hbm2ddl: validate
#      show-sql: true
#    hibernate:
#      ddl-auto: validate #update   create-drop  create validate
#    show-sql: true